# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d1e737f29ec725d41b90c4fc2fe8e20c95c95210c1c1892c4d8ef05f0fd3e7762922bdbb3c41fa79edfd58fdd2b06d22104fef632f084949c15d22e3defd4bc
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 4989e7adb9bae085e2bc41b1ba98ef5920bd6197bf89f9d6452a66dedc0347ef8748eedb0c442bdb4d1b56c353389dc9b528bf1730d4cb79fc75311df39d881f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 